name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: Pyrrha-Z
          
      - name: Initialize
        working-directory: Pyrrha-Z
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../rtos/zephyr/scripts/requirements-base.txt

      - name: Run Tests
        working-directory: Pyrrha-Z
        run: |
          ../rtos/zephyr/scripts/twister -v --tag pyrrha -T .
        env:
          CMAKE_PREFIX_PATH: /opt/toolchains

      - name: Build firmware
        working-directory: Pyrrha-Z
        run: |
          west build -b nrf52840dk_nrf52840 -s app
        env:
          CMAKE_PREFIX_PATH: /opt/toolchains
